WebUI/Controllers/FarmerRegistrationController.cs
using BirsaKisanApp.DomainLayer.Entities;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace BirsaKisanApp.PresentaionLayer.WebUI.Controllers
{
    public class FarmerRegistrationController : Controller
    {
        string? ConnectionString;
        private readonly IConfiguration _configuration;
        public FarmerRegistrationController(IConfiguration configuration)
        {
            _configuration = configuration;
            ConnectionString = _configuration.GetConnectionString("DapperConnection");
        }
        public IActionResult Index(Lgdcode code)
        {
            List<Lgdcode> dummyData = new List<Lgdcode>
            {
                new Lgdcode { DistrictId = 1, DistrictName = "District 1", BlockId = 101, BlockName = "Block 1", VillageId = 1001, VillageName = "Village 1" },
                new Lgdcode { DistrictId = 1, DistrictName = "District 1", BlockId = 102, BlockName = "Block 2", VillageId = 1002, VillageName = "Village 2" },
                new Lgdcode { DistrictId = 2, DistrictName = "District 2", BlockId = 201, BlockName = "Block 1", VillageId = 2001, VillageName = "Village 1" },
                new Lgdcode { DistrictId = 2, DistrictName = "District 2", BlockId = 202, BlockName = "Block 2", VillageId = 2002, VillageName = "Village 2" },
                // Add more dummy data as needed
            };
            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();
                try
                {
                    string query = "SELECT Id, ProjectName, UrlName, PersonInCharge, ContactNumber, Email from [dbo].[APIManagement]";

                    // Execute the query and retrieve the results
                    List<Lgdcode> apiData = connection.Query<Lgdcode>(query).ToList();
                    connection.Close();
                    return View(apiData);

                }
                catch (Exception ex)
                {
                    return Ok(new { Error = ex.Message });
                }
            }
            return View(dummyData);
        }
    }
}

WebUI/Views/FarmerRegistration/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_SecondLayout.cshtml";

}
@model List<BirsaKisanApp.DomainLayer.Entities.Lgdcode>

 <div class="d-flex justify-content-around mt-5">

    <div class="card" style="width: 28rem;">
        <div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="DistrictDropDown" data-bs-toggle="dropdown" aria-expanded="false">
                    @Model.First().DistrictName
                </button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="DistrictDropDown">
                    @foreach (var item in Model)
                    {
                        <li><a class="link-offset-2 link-underline link-underline-opacity-0" href="@Url.Action("Index","FarmerRegistration",new {id=item.DistrictId})">@item.DistrictName</a></li>
                    }
                </ul>
            </div>
        </div>
        <div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="BlockDropDown" data-bs-toggle="dropdown" aria-expanded="false">
                    @Model.First().BlockName
                </button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="BlockDropDown">
                    @foreach (var item in Model)
                    {
                        <li><a class="link-offset-2 link-underline link-underline-opacity-0" href="@Url.Action("Index","FarmerRegistration",new {id=item.DistrictId})">@item.DistrictName</a></li>
                    }
                </ul>
            </div>
        </div>
        <div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="VillageDropDown" data-bs-toggle="dropdown" aria-expanded="false">
                    @Model.First().BlockName
                </button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="VillageDropDown">
                    @foreach (var item in Model)
                    {
                        <li><a class="btn btn-light form-control" href="@Url.Action("Index","FarmerRegistration",new {id=item.DistrictId})">@item.DistrictName</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>

 </div>