WebUI/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using BirsaKisanApp.DomainLayer.Entities;
using Dapper;

namespace BirsaKisanApp.PresentaionLayer.WebUI.Controllers
{

    public class AdminController : Controller
    {
        private readonly IConfiguration _configuration;
        string? ConnectionString;

        public AdminController(IConfiguration configuration)
        {
            _configuration = configuration;
            ConnectionString = _configuration.GetConnectionString("DapperConnection");
        }

        [Authorize]
        public IActionResult Index()
        {

            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();
                try
                {
                    string query = "SELECT Id, ProjectName, UrlName, PersonInCharge, ContactNumber, Email from [dbo].[APIManagement]";

                    // Execute the query and retrieve the results
                    List<APIDetails> apiData = connection.Query<APIDetails>(query).ToList();
                    connection.Close();
                    return View(apiData);

                    

                }
                catch (Exception ex)
                {
                    return Ok(new { Error = ex.Message });
                }
            }

        }
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(APIDetails form)
        {


            if (ModelState.IsValid)
            {
                using (var connection = new SqlConnection(ConnectionString))
                {
                    connection.Open();
                    try
                    {
                        string query = "INSERT INTO [dbo].[APIManagement] (ProjectName, UrlName, PersonInCharge, ContactNumber, Email, CreatedDate,UpdatedTime) VALUES (@ProjectName, @UrlName, @PersonInCharge, @ContactNumber, @Email, GetDate(),GetDate());";

                        // Execute the query and retrieve the results
                        APIDetails apiDetail = connection.Query<APIDetails>(query, form).FirstOrDefault();
                        connection.Close();
                        return RedirectToAction("Index");

                    }
                    catch (Exception ex)
                    {
                        return Ok(new { Error = ex.Message });
                    }

                }
            }
            return View(form);
        }
        [Authorize]
        public IActionResult Edit(int Id)
        {
            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();
                try
                {
                    string query = "SELECT Id, ProjectName, UrlName, PersonInCharge, ContactNumber, Email from [dbo].[APIManagement] where Id =@Id";

                    // Execute the query and retrieve the results
                    APIDetails apiDetail = connection.Query<APIDetails>(query, new { Id }).FirstOrDefault();
                    connection.Close();
                    return View(apiDetail);

                }
                catch (Exception ex)
                {
                    return Ok(new { Error = ex.Message });
                }
            }
        }
        [Authorize]
        [HttpPost]
        public IActionResult Edit(APIDetails form)
        {
            // Handle form submission (e.g., save to database)
            if (ModelState.IsValid)
            {
                using (var connection = new SqlConnection(ConnectionString))
                {
                    connection.Open();
                    try
                    {
                        string query = "UPDATE APIManagement SET ProjectName = @ProjectName, UrlName = @UrlName, PersonInCharge = @PersonInCharge, ContactNumber = @ContactNumber, Email =@Email, UpdatedTime = GETDATE() WHERE Id = @Id;";

                        // Execute the query and retrieve the results
                        APIDetails apiDetail = connection.Query<APIDetails>(query, form).FirstOrDefault();
                        connection.Close();
                        return RedirectToAction("Index");

                    }
                    catch (Exception ex)
                    {
                        return Ok(new { Error = ex.Message });
                    }
                    
                }
            }
            return View(form);
        }
            [Authorize]
            public IActionResult Delete(int Id)
            {
            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();
                try
                {
                    string query = "DELETE FROM [dbo].[APIManagement] where Id =@Id";

                    // Execute the query and retrieve the results
                    APIDetails apiDetail = connection.Query<APIDetails>(query, new { Id }).FirstOrDefault();
                    connection.Close();
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    return Ok(new { Error = ex.Message });
                }
            }
        }
        
    }
}

WebUI/Views/Admin/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model BirsaKisanApp.DomainLayer.Entities.APIDetails

<form asp-action="Create" method="post" class="my-3">
    <div>
        <label class="form-check-label" asp-for="ProjectName">Project Name:</label>
        <input class="form-control" asp-for="ProjectName" autocomplete="off" />
    </div>
    <div>
        <label class="form-check-label" asp-for="UrlName">URL Name:</label>
        <input class="form-control" asp-for="UrlName" autocomplete="off" />
    </div>
    <div>
        <label class="form-check-label" asp-for="PersonInCharge">Person in Charge:</label>
        <input class="form-control" asp-for="PersonInCharge" autocomplete="off" />
    </div>
    <div>
        <label class="form-check-label" asp-for="ContactNumber">Contact Number:</label>
        <input class="form-control" asp-for="ContactNumber" autocomplete="off" />
    </div>
    <div>
        <label class="form-check-label" asp-for="Email">Email:</label>
        <input class="form-control" asp-for="Email" autocomplete="off" type="email" id="email" name="email" required />
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>

WebUI/Views/Admin/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Delete</h1>

WebUI/Views/Admin/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model BirsaKisanApp.DomainLayer.Entities.APIDetails

<form asp-action="Edit" method="post" class="my-3">
    <div>
        <label class="form-check-label" asp-for="ProjectName">Project Name:</label>
        <input class ="form-control" asp-for="ProjectName" />
    </div>
    <div>
        <label class="form-check-label" asp-for="UrlName">URL Name:</label>
        <input class="form-control" asp-for="UrlName" />
    </div>
    <div>
        <label class="form-check-label" asp-for="PersonInCharge">Person in Charge:</label>
        <input class="form-control"  asp-for="PersonInCharge" />
    </div>
    <div>
        <label class="form-check-label" asp-for="ContactNumber">Contact Number:</label>
        <input class="form-control" asp-for="ContactNumber" />
    </div>
    <div>
        <label class="form-check-label" asp-for="Email">Email:</label>
        <input class="form-control" asp-for="Email" />
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>

WebUI/Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}
@model List<BirsaKisanApp.DomainLayer.Entities.APIDetails>


<div class="container">
    <div class="d-flex justify-content-end">
        <a type="button" class="btn btn-outline-success my-3" href="@Url.Action("Create","Admin")">+ Add Record</a>

    </div>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                
                <th scope="col">ProjectName</th>
                <th scope="col">Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    
                    <td>@item.ProjectName</td>
                    <td>@item.UrlName</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="@Url.Action("Edit","Admin",new {id=item.Id})">Edit</a>
                        <a class="btn btn-sm btn-danger" href="@Url.Action("Delete","Admin",new {id=item.Id})">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
@*     <div class="d-flex justify-content-end">
        <input type="text" placeholder="Enter Id..." />
        <button type="button" class="btn btn-primary">Get Record and update</button>
    </div> *@

</div>

<br />
<br />
<br />
<br />
<br />