WebUI/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebUI.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

WebUI/Controllers/DirectorateController.cs
using Microsoft.AspNetCore.Mvc;

namespace BirsaKisanApp.PresentaionLayer.WebUI.Controllers
{
    public class DirectorateController : Controller
    {
        public IActionResult Agriculture()
        {
            return View();
        }
        public IActionResult Horticulture()
        {
            return View();
        }
        public IActionResult SoilConservation()
        {
            return View();
        }
        public IActionResult Cooperative()
        {
            return View();
        }
        public IActionResult AnimalHusbandry()
        {
            return View();
        }
        public IActionResult Fisheries()
        {
            return View();
        }
        public IActionResult Dairy()
        {
            return View();
        }
        public IActionResult JSAMB()
        {
            return View();
        }
    }
}

WebUI/Controllers/FarmerRegistrationController.cs
using BirsaKisanApp.DomainLayer.Entities;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace BirsaKisanApp.PresentaionLayer.WebUI.Controllers
{
    public class FarmerRegistrationController : Controller
    {
        string? ConnectionString;
        private readonly IConfiguration _configuration;
        public FarmerRegistrationController(IConfiguration configuration)
        {
            _configuration = configuration;
            ConnectionString = _configuration.GetConnectionString("DapperConnection");
        }
        public IActionResult Index(Lgdcode code)
        {
            List<Lgdcode> dummyData = new List<Lgdcode>
            {
                new Lgdcode { DistrictId = 1, DistrictName = "District 1", BlockId = 101, BlockName = "Block 1", VillageId = 1001, VillageName = "Village 1" },
                new Lgdcode { DistrictId = 1, DistrictName = "District 1", BlockId = 102, BlockName = "Block 2", VillageId = 1002, VillageName = "Village 2" },
                new Lgdcode { DistrictId = 2, DistrictName = "District 2", BlockId = 201, BlockName = "Block 1", VillageId = 2001, VillageName = "Village 1" },
                new Lgdcode { DistrictId = 2, DistrictName = "District 2", BlockId = 202, BlockName = "Block 2", VillageId = 2002, VillageName = "Village 2" },
                // Add more dummy data as needed
            };
            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();
                try
                {
                    string query = "SELECT Id, ProjectName, UrlName, PersonInCharge, ContactNumber, Email from [dbo].[APIManagement]";

                    // Execute the query and retrieve the results
                    List<Lgdcode> apiData = connection.Query<Lgdcode>(query).ToList();
                    connection.Close();
                    return View(apiData);

                }
                catch (Exception ex)
                {
                    return Ok(new { Error = ex.Message });
                }
            }
            return View(dummyData);
        }
    }
}

WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace BirsaKisanApp.PresentationLayer.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        #region Localization
        public IActionResult ChangeLanguage(string culture)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });

            return Redirect(Request.Headers["Referer"].ToString());
        }
        #endregion

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }
        
        public IActionResult Dashboard()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Status()
        {
            return View();
        }
        
    }
}

WebUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="" style="background-color:#78935E;">
    <marquee width="100%" behavior="alternate" bgcolor="#9EA91C" class="text-white">
        This is the news that will be flashed
    </marquee>
    <marquee width="100%" direction="right" bgcolor="#78935E" class="text-white">
        पोर्टल के संदर्भ में इस 1800-123-1136 टोल फ्री नंबर पर कॉल करें ।
    </marquee>
</div>

<div class="container">
    <div class="d-flex justify-content-center rounded-pill m-2 pt-2" style="background-color:#244702;">
        <h2 class="text-white px-5">
            <b>जोहार झारखंड</b>
        </h2>
    </div>
</div>
<div class="container">
    <div class="d-flex justify-content-start">
        <div class="rounded-pill m-2 pt-2" style="background-color:#244702;">
            <h2 class="text-white px-5">
                <b>@_localization.GetNameTag("importantschemes") </b>
            </h2>
        </div>
    </div>

    <div style="border: none;background:white;">
        <div class="container" data-aos="fade-up">
            <div class="row pb-5">
                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b> <a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="Agriculture">@_localization.GetNameTag("Agriculture")</a></b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("AgricultureSchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AgricultureSchemes2")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AgricultureSchemes3")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AgricultureSchemes4")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AgricultureSchemes5")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AgricultureSchemes6")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b><a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="Horticulture">@_localization.GetNameTag("Horticulture")</a></b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("HorticultureSchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("HorticultureSchemes2")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b>
                            <a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="SoilConservation">@_localization.GetNameTag("SoilConservation")</a>
                        </b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("SoilConservationSchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("SoilConservationSchemes2")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("SoilConservationSchemes3")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("SoilConservationSchemes4")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b><a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="Cooperative">@_localization.GetNameTag("Cooperative") </a></b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("CooperativeSchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("CooperativeSchemes2")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("CooperativeSchemes3")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("CooperativeSchemes4")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("CooperativeSchemes5")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b>
                            <a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="AnimalHusbandry">@_localization.GetNameTag("AnimalHusbandry")</a>
                        </b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("AnimalHusbandrySchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AnimalHusbandrySchemes2")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("AnimalHusbandrySchemes3")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b><a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="Fisheries">@_localization.GetNameTag("Fisheries")</a></b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("FisheriesSchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("FisheriesSchemes2")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("FisheriesSchemes3")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("FisheriesSchemes4")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b><a class="link-underline link-underline-opacity-0 text-white" asp-controller="Directorate" asp-action="Dairy">@_localization.GetNameTag("Dairy")</a></b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("DairySchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("DairySchemes2")</li>
                        </ol>
                    </div>

                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <h3 class="text-white px-5 py-2" style="background-color:#244702;">
                        <b>
                            <a class="link-underline-opacity-10 text-white" asp-controller="Directorate" asp-action="JSAMB">@_localization.GetNameTag("JSAMB")</a>
                        </b>
                    </h3>
                    <div class=" rounded-3" data-aos="zoom-in" data-aos-delay="100">
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item ">@_localization.GetNameTag("JSAMBSchemes1")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("JSAMBSchemes2")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("JSAMBSchemes3")</li>
                            <li class="list-group-item ">@_localization.GetNameTag("JSAMBSchemes4")</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

WebUI/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = @_localization.GetNameTag("ContactUs");
}

<div class="container heroSection">
    <h1 data-aos="fade-left">@_localization.GetNameTag("ContactUs")</h1>
</div>
<!-- Department Introduction -->
<!-- ======= Contact Section ======= -->
<div class="contactList">
    <ol class="NameList">
        <li>
            <strong>Shri Aboobacker Siddique P, IAS</strong>
            <p>
                Secretary
                Department of Agriculture, Animal Husbandry & Co-operative,
                Government of Jharkhand
            </p>
            <p><b>Email id:</b>jhagriculture[at]gmail[dot]com</p>
            <p><b>Phone Number:</b>06512490578</p>
            <p>
                <b>Address:</b>1st Floor Nepal House, Doranda,
                Ranchi-Jharkhand
                PIN: 834002
            </p>
        </li>
        <li>
            <strong>Shri Pradeep Kumar Hazari</strong>
            <p>
                Special Secretary cum Adviser,
                Department of Agriculture,
                Animal Husbandry and Co-operative,
                Government of Jharkhand
            </p>
            <p><b>Email id:</b>advisercell[at]gmail[dot]com</p>
            <p><b>Phone Number:</b>0651-2490024</p>
            <p>
                <b>Address:</b>1st Floor Nepal House, Doranda,
                Ranchi-Jharkhand
                PIN: 834002
            </p>
        </li>
        <li>
            <strong>Shri Gopal Jee Tiwari</strong>
            <p>
                Joint Secretary,
                Department of Agriculture,
                Animal Husbandry and Co-operative,
                Government of Jharkhand
            </p>
            <p><b>Email id:</b>agrisoil123[at]gmail[dot]com</p>
            <p><b>Phone Number:</b>0651-2490024</p>
            <p>
                <b>Address:</b>1st Floor Nepal House, Doranda,
                Ranchi-Jharkhand
                PIN: 834002
            </p>
        </li>

        <li>
            <strong>Shri Kumar Tarachand, IAS</strong>
            <p>
                Director Cum Nodal Officer,
                Directorate of Agriculture,
                Department of Agriculture,
                Animal Husbandry and Co-operative,
                Government of Jharkhand
            </p>
            <p><b>Email id:</b>directoragriculturejh [at]gmail [dot]com</p>
            <p><b>Phone Number:</b>0651-2233549</p>
            <p>
                <b>Address:</b>1st floor, Krishi Bhawan, Kanke Road
                Ranchi- 834008
            </p>
        </li>

        <li>
            <strong>Shri Suraj Kumar (IAS)</strong>
            <p>
                Director Cooperative,
                Directorate of Agriculture,
                Department of Agriculture,
                Animal Husbandry and Co-operative,
                Government of Jharkhand
            </p>
            <p><b>Email id:</b>jharkhand.coopregistrar@gmail.com</p>
            @* <p><b>Phone Number:</b>0651-2233549</p> *@
            <p>
                <b>Address:</b>Registrar, Cooperative Societies
                3rd Floor, Pashupalan and Sahkarita Bhawan,
                Hesag, Hatia, Ranchi - 834003
            </p>
        </li>
    </ol>
</div>

WebUI/Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
    </div>
    <div class="row my-5">
        <div class="col-6">
            <canvas id="myChart1" style="width:100%;max-width:600px"></canvas>
        </div>
        <div class="col-6">
            <canvas id="myChart2" style="width:100%;max-width:600px"></canvas>
        </div>
        <div class="col-12 d-flex justify-content-center">
            <canvas id="myChart4" style="width:100%;max-width:600px"></canvas>
        </div>
        <div class="col-6">
            <canvas id="myChart3" style="width:100%;max-width:600px"></canvas>
        </div>
        <div class="col-6">
            <canvas id="myChart5" style="width:100%;max-width:600px"></canvas>
        </div>
        <div class="col-12 d-flex justify-content-center">
            <table class="table table-striped">
            <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">District</th>
            <th scope="col">Total</th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <th scope="row">1</th>
            <td>Bokaro</td>
            <td>55</td>
            </tr>
            <tr>
            <th scope="row">2</th>
            <td>Chatra</td>
            <td>12</td>
            </tr>
            <tr>
            <th scope="row">3</th>
            <td>Deoghar</td>
            <td>34</td>
            </tr>
            <tr>
            <th scope="row">4</th>
            <td>Dhanbad</td>
            <td>45</td>
            </tr>
            <tr>
            <th scope="row">5</th>
            <td>Dumka</td>
            <td>45</td>
            </tr>
            <tr>
            <th scope="row">6</th>
            <td>Jamshedpur</td>
            <td>45</td>
            </tr>
            </tbody>
            </table> 
        </div>
    </div>
</div>
<script>
    const xValues = ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "Jamshedpur", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Kodarma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Saraikela", "Simdega", "West Singhbhum"];
    const yValues = [55, 49, 44, 24, 15, 55, 49, 44, 24, 15, 45, 98, 55, 49, 44, 24, 15, 55, 49, 44, 24, 15, 45, 98,76,87];
    const barColors = ["red", "green", "blue", "orange", "brown", "red", "green", "blue", "orange", "brown", "red", "green", "blue", "orange", "brown", "red", "green", "blue", "orange", "brown", "red", "green", "blue", "orange", "brown", "red", "green", "blue", "orange", "brown"];

    new Chart("myChart1", {
        type: "line",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            legend: { display: false },
            title: {
                display: true,
                text: "District wise report"
            }
        }
    });
    new Chart("myChart2", {
        type: "bar",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            legend: { display: false },
            title: {
                display: true,
                text: "District wise report"
            }
        }
    });

    new Chart("myChart3", {
        type: "pie",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            legend: { display: false },
            title: {
                display: true,
                text: "District wise report"
            }
        }
    });
    new Chart("myChart4", {
        type: "polarArea",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            legend: { display: false },
            responsive: true,
            title: {
                display: true,
                text: "District wise report"
            }
        }
    });
    new Chart("myChart5", {
        type: "horizontalBar",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            legend: { display: false },
            responsive: true,
            title: {
                display: true,
                text: "District wise report"
            }
        }
    });
</script>

WebUI/Views/Home/Login.cshtml
@{
    Layout = "~/Views/Shared/_SecondLayout.cshtml";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@_localization.GetNameTag("LogIn")</title>
</head>
<body>
    <div class="d-flex justify-content-center align-items-center">
        <div class="card mt-5" style="width: 28rem;">
            <div class="card-body">
                <form>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">User Email</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">I agree </label>
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </form>
            </div>
        </div>
        <div>
            
        </div>
    </div>
</body>
</html>